name: dff-ai-faq-ru-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8190
      SERVICE_NAME: dff_ai_faq_ru_prompted_skill
      PROMPT_FILE: common/prompts/ai_faq_ru.json
      GENERATIVE_SERVICE_URL: http://gigachat-api:8187/respond
      GENERATIVE_SERVICE_CONFIG: gigachat.json
      GENERATIVE_TIMEOUT: 120
      N_UTTERANCES_CONTEXT: 7
      ENVVARS_TO_SEND: GIGACHAT_CREDENTIAL,GIGACHAT_SCOPE
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8190:8190
proxy: null
