name: emotion-detection
endpoints:
- model
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8045
      SERVICE_NAME: emotion_detection
    context: .
    dockerfile: ./annotators/emotion_detection/Dockerfile
  command: uvicorn server:app --host 0.0.0.0 --port 8045
  deploy:
    resources:
      limits:
        memory: 1G
      reservations:
        memory: 1G
  volumes:
  - ./annotators/emotion_detection:/src/drm
  ports:
  - 8045:8045