name: emotion-detection
endpoints:
- model
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8027
      SERVICE_NAME: emotion_detection
      CUDA_VISIBLE_DEVICES: 0
    context: .
    dockerfile: ./annotators/emotion_detection/Dockerfile
  command: uvicorn server:app --host 0.0.0.0 --port 8027
  deploy:
    resources:
      limits:
        memory: 1G
      reservations:
        memory: 1G
  volumes:
  - ./annotators/emotion_detection:/src/drm
  ports:
  - 8027:8027