name: wkai9w4cr05s
endpoints:
- respond
compose:
  image: null
  volumes:
  - .:/dp-agent
  env_file: null
  build: null
  command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/project_manager/pipeline_conf.json'
  environment: null
  deploy:
    mode: null
    replicas: null
    resources:
      limits:
        memory: 200M
      reservations:
        memory: 200M
  tty: null
  ports: null
proxy: null
