name: convert-based-nli
endpoints:
- batch_model
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8150
      SERVICE_NAME: convert_based_nli
      TRAINED_MODEL_PATH: /data/nli_model
      FLASK_APP: server
    context: annotators/ConveRTBasedNLI/
  command: flask run -h 0.0.0.0 -p 8150
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 1.5G
      reservations:
        memory: 1.5G
  volumes:
  - ./annotators/ConveRTBasedNLI:/src
  - ./common:/src/common
  ports:
  - 8150:8150
proxy: null