name: dff-journalist-helper-ru-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env_ru
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8175
      SERVICE_NAME: dff_official_letter_ru_prompted_skill
      PROMPT_FILE: common/prompts/official_letter_ru.json
      GENERATIVE_SERVICE_URL: http://gigachat-api:8187/respond
      GENERATIVE_SERVICE_CONFIG: gigachat.json
      GENERATIVE_TIMEOUT: 20
      N_UTTERANCES_CONTEXT: 3
      ENVVARS_TO_SEND: GIGACHAT_CREDENTIAL,GIGACHAT_SCOPE
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8175:8175
proxy: null
