# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  convers-evaluator-annotator:
    volumes:
      - "./annotators/ConversationEvaluator:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8004:8004
  spacy-nounphrases:
    volumes:
      - "./annotators/spacy_nounphrases:/src"
      - "./common:/src/common"
    ports:
      - 8006:8006
  rake-keywords:
    volumes:
      - "./annotators/rake_keywords:/src"
    ports:
      - 8007:8007
  dff-program-y-skill:
    volumes:
      - "./skills/dff_program_y_skill:/src"
      - "./common:/src/common"
    ports:
      - 8008:8008
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  convers-evaluation-selector:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  sentrewrite:
    volumes:
      - "./annotators/SentRewrite:/src"
    ports:
      - 8017:8017
  intent-catcher:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8014:8014
  badlisted-words:
    volumes:
      - "./annotators/BadlistedWordsDetector:/src"
      - "./common:/src/common"
    ports:
      - 8018:8018
  ner:
    volumes:
      - './annotators/NER_deeppavlov:/src'
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8021:8021
  asr:
    volumes:
      - "./annotators/asr:/src"
      - "./common:/src/common"
    ports:
      - 8031:8031
  comet-atomic:
    volumes:
      - "./annotators/COMeT:/src"
      - "./common:/src/common"
    ports:
      - 8053:8053
  comet-conceptnet:
    volumes:
      - "./annotators/COMeT:/src"
      - "./common:/src/common"
    ports:
      - 8065:8065
  news-api-annotator:
    volumes:
      - "./annotators/news_api:/src"
      - "./common:/src/common"
    ports:
      - 8112:8112
  kbqa:
    volumes:
      - "./annotators/kbqa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8072:8072
  entity-linking:
    volumes:
      - "./annotators/entity_linking:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8075:8075
  wiki-parser:
    volumes:
      - "./annotators/wiki_parser:/src"
      - "./common:/src/common"
    ports:
      - 8077:8077
  mongo:
    ports:
      - 27017:27017
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  spelling-preprocessing:
    volumes:
      - "./annotators/spelling_preprocessing:/src"
    ports:
      - 8074:8074
  text-qa:
    volumes:
      - "./services/text_qa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8078:8078
  knowledge-grounding:
    volumes:
      - "./services/knowledge_grounding:/src"
    ports:
      - 8083:8083
  dff-friendship-skill:
    volumes:
      - "./skills/dff_friendship_skill:/src"
      - "./common:/src/common"
    ports:
      - 8086:8086
  entity-storer:
    volumes:
      - "./common:/src/common"
      - "./annotators/entity_storer:/src"
    ports:
      - 8089:8089
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8087:8087
  midas-classification:
    volumes:
      - "./annotators/midas_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8090:8090
  fact-random:
    volumes:
      - "./annotators/fact_random:/src"
      - "./common:/src/common"
    ports:
      - 8119:8119
  fact-retrieval:
    volumes:
      - "./annotators/fact_retrieval:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8100:8100
  topic-recommendation:
    volumes:
      - "./annotators/topic_recommendation:/src"            
    ports:
      - 8113:8113
  user-persona-extractor:
    volumes:
      - "./annotators/user_persona_extractor:/src"
      - "./common:/src/common"
    ports:
      - 8114:8114
  wiki-facts:
    volumes:
      - "./services/wiki_facts:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8116:8116
  entity-detection:
    volumes:
      - "./annotators/entity_detection:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8103:8103
  midas-predictor:
    volumes:
      - "./annotators/midas_predictor:/src"
    ports:
      - 8121:8121
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128
  relative-persona-extractor:
    volumes:
      - "./annotators/relative_persona_extractor:/src"
      - "./common:/src/common"
    ports:
      - 8133:8133
  dff-template-skill:
    volumes:
      - "./skills/dff_template_skill:/src"
      - "./common:/src/common"
    ports:
      - 8120:8120
version: "3.7"
