# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  
  spelling-preprocessing:
    volumes:
      - "./annotators/spelling_preprocessing:/src"
    ports:
      - 8074:8074
    
  dff-program-y-skill:
    volumes:
      - "./skills/dff_program_y_skill:/src"
      - "./common:/src/common"
    ports:
      - 8008:8008
      
  badlisted-words:
    volumes:
      - "./annotators/BadlistedWordsDetector:/src"
      - "./common:/src/common"
    ports:
      - 8018:8018
  # mongo:
  #   ports:
  #     - 27017:27017
  #   # # you can use persistent local volume if you need
  #   # volumes:
  #   #   - ./venv/data/db_data:/root/data/db
  # spelling-preprocessing:
  #   volumes:
  #     - "./annotators/spelling_preprocessing:/src"
  #   ports:
  #     - 8074:8074
  dff-friendship-skill:
    volumes:
      - "./skills/dff_friendship_skill:/src"
      - "./common:/src/common"
    ports:
      - 8086:8086

  faq-skill:
    build:
      context: skills/faq_skill_deepy
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3772 --timeout=1000
    ports:
      - 3710:3710
  
  dff-template-skill:
    volumes:
      - "./skills/dff_template_skill:/src"
      - "./common:/src/common"
    ports:
      - 8120:8120
version: "3.7"
