SERVICE_PORT: 8182
SERVICE_NAME: skill_selector
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 20
N_UTTERANCES_CONTEXT: 3
PROMPT_FILE: common/prompts/skill_selector.json
FLASK_APP: server