SERVICE_PORT: 8182
SERVICE_NAME: skill_selector
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 20
N_UTTERANCES_CONTEXT: 3
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
PROMPT_FILE: common/prompts/skill_selector.json
MAX_N_SKILLS: 3
FLASK_APP: server