services:
  agent:
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/dream_persona_ru_prompted/pipeline_conf.json'
    environment:
      WAIT_HOSTS: "no-restrictions-selector-ru:8009, badlisted-words-ru:8018,
          dialogrpt-ru:8122, prompt-selector-ru:8135, transformers-lm-llama7bru:8149, 
          dff-dream-persona-llama7bru-prompted-skill:8151"
      WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-1800}
      HIGH_PRIORITY_INTENTS: 0
      RESTRICTION_FOR_SENSITIVE_CASE: 0
      ALWAYS_TURN_ON_ALL_SKILLS: 0
      LANGUAGE: RU

  no-restrictions-selector-ru:
    env_file: [ .env ]
    build:
      args:
        TAG_BASED_SELECTION: 1
        CALL_BY_NAME_PROBABILITY: 0.5
        PROMPT_PROBA: 0
        ACKNOWLEDGEMENT_PROBA: 0.3
        PRIORITIZE_WITH_REQUIRED_ACT: 0
        PRIORITIZE_NO_DIALOG_BREAKDOWN: 0
        PRIORITIZE_WITH_SAME_TOPIC_ENTITY: 0
        IGNORE_DISLIKED_SKILLS: 0
        GREETING_FIRST: 0
        RESTRICTION_FOR_SENSITIVE_CASE: 0
        PRIORITIZE_PROMTS_WHEN_NO_SCRIPTS: 0
        MAX_TURNS_WITHOUT_SCRIPTS: 100
        ADD_ACKNOWLEDGMENTS_IF_POSSIBLE: 0
        PRIORITIZE_SCRIPTED_SKILLS: 0
        CONFIDENCE_STRENGTH: 0.8
        CONV_EVAL_STRENGTH: 0.4
        PRIORITIZE_HUMAN_INITIATIVE: 1
        QUESTION_TO_QUESTION_DOWNSCORE_COEF: 0.8
        LANGUAGE: RU
      context: .
      dockerfile: ./response_selectors/convers_evaluation_based_selector/Dockerfile
    command: flask run -h 0.0.0.0 -p 8009
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M

  badlisted-words-ru:
    env_file: [ .env_ru ]
    build:
      args:
        SERVICE_PORT: 8018
        SERVICE_NAME: badlisted_words
      context: annotators/BadlistedWordsDetector_ru/
    command: flask run -h 0.0.0.0 -p 8018
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

  dialogrpt-ru:
    env_file: [ .env_ru ]
    build:
      context: ./services/dialogrpt_ru/
      args:
        SERVICE_PORT: 8122
        PRETRAINED_MODEL_FNAME: dialogrpt_ru_ckpt_v0.pth
        TOKENIZER_NAME_OR_PATH: DeepPavlov/rudialogpt3_medium_based_on_gpt2_v2
    command: flask run -h 0.0.0.0 -p 8122
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G

  prompt-selector-ru:
    env_file: [ .env_ru ]
    build:
      args:
        SERVICE_PORT: 8135
        SERVICE_NAME: prompt_selector
        N_SENTENCES_TO_RETURN: 3
        PROMPTS_TO_CONSIDER: dream_persona_ru
      context: .
      dockerfile: ./annotators/prompt_selector/Dockerfile
    command: flask run -h 0.0.0.0 -p 8135
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M

  transformers-lm-llama7bru:
    env_file: [ .env_ru ]
    build:
      args:
        SERVICE_PORT: 8149
        SERVICE_NAME: transformers_peft_lm_llama7bru
        PRETRAINED_MODEL_NAME_OR_PATH: IlyaGusev/llama_7b_ru_turbo_alpaca_lora
        LANGUAGE: RU
      context: .
      dockerfile: ./services/transformers_peft_lm/Dockerfile
    command: flask run -h 0.0.0.0 -p 8149
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 50G
        reservations:
          memory: 50G

  dff-dream-persona-llama7bru-prompted-skill:
    env_file: [ .env_ru ]
    build:
      args:
        SERVICE_PORT: 8151
        SERVICE_NAME: dff_dream_persona_ru_prompted_skill
        PROMPT_FILE: common/prompts/dream_persona_ru.json
        GENERATIVE_SERVICE_URL: http://transformers-lm-llama7bru:8149/respond
        GENERATIVE_TIMEOUT: 10
        N_UTTERANCES_CONTEXT: 3
      context: .
      dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8151 --reload
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

version: '3.7'
