SERVICE_PORT: 8187
SERVICE_NAME: skill_selector
DEFAULT_LM_SERVICE_URL: http://openai-api-chatgpt:8145/respond
DEFAULT_LM_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 20
N_UTTERANCES_CONTEXT: 3
FLASK_APP: server