entity-storer:
  annotators:
    connector:
      protocol: http
      timeout: 1.0
      url: http://entity-storer:8089/respond
    dialog_formatter: state_formatters.dp_formatters:entity_storer_formatter
    response_formatter: state_formatters.dp_formatters:simple_formatter_service
    previous_services:
    - annotators.combined_classification
    - annotators.entity_detection
    state_manager_method: update_attributes
