name: external-integration-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8171
      SERVICE_NAME: external_integration_skill
      EXTERNAL_SKILL_URL: http://external-fake-server:8172/return_response
      ARGUMENTS_TO_SEND: dialog_id
      PAYLOAD_ARGUMENT_NAME: payload
      RESPONSE_KEY: response
      REQUEST_TIMEOUT: 10
    context: .
    dockerfile: ./skills/external_integration_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:$8171 --timeout=300
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/external_integration_skill:/src
  - ./common:/src/common
  ports:
  - 8171:8171
