SERVICE_PORT: 8152
SERVICE_NAME: dff_deepy_prompted_skill
PROMPT_FILE: common/prompts/deepy.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8131/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
