services:

  combined-classification:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=gpu8.ipavlov.mipt.ru:8087
      - PORT=8087

  sentence-ranker:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=gpu8.ipavlov.mipt.ru:8128
      - PORT=8128

  transformers-lm-gptj:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=gpu8.ipavlov.mipt.ru:8130
      - PORT=8130

  transformers-lm-bloomz7b:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=gpu8.ipavlov.mipt.ru:8146
      - PORT=8146

version: '3.7'
