# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242

  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 9011:9011
  ranking-and-intent-based-response-selector:
    volumes:
      - "./response_selectors/ranking_and_intent_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 9081:9081
  dff-intent-responder-skill:
    volumes:
      - "./skills/dff_intent_responder_skill:/src"
      - "./common:/src/common"
    ports:
      - 9012:9012
  dialogpt:
    volumes:
      - "./services/dialogpt:/src"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 9125:9125
  intent-catcher:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 9014:9014
  ner:
    volumes:
      - './annotators/NER_deeppavlov:/src'
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 9021:9021
  factoid-qa:
    volumes:
      - "./skills/factoid_qa:/src"
      - "./common:/src/common"
    ports:
      - 9071:9071
  kbqa:
    volumes:
      - "./annotators/kbqa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 9072:9072
  entity-linking:
    volumes:
      - "./annotators/entity_linking:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 9075:9075
  wiki-parser:
    volumes:
      - "./annotators/wiki_parser:/src"
      - "./common:/src/common"
    ports:
      - 9077:9077
  mongo:
    ports:
      - 37017:37017
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  text-qa:
    volumes:
      - "./services/text_qa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 9078:9078
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 9087:9087
  openai-api-chatgpt:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 9145:9145
  fact-retrieval:
    volumes:
      - "./annotators/fact_retrieval:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 9100:9100
  entity-detection:
    volumes:
      - "./annotators/entity_detection:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 9103:9103
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 9128:9128
  prompt-selector:
    volumes:
      - "./annotators/prompt_selector:/src"
      - "./common:/src/common"
    ports:
      - 9135:9135
  dff-dream-persona-chatgpt-prompted-skill:
    volumes:
      - "./skills/dff_template_prompted_skill:/src"
      - "./common:/src/common"
    ports:
      - 9137:9137
  property-extraction:
    volumes:
      - "./annotators/property_extraction:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 9136:9136
  dff-dream-faq-prompted-skill:
    volumes:
      - "./skills/dff_template_prompted_skill:/src"
      - "./common:/src/common"
    ports:
      - 9170:9170
  summarization-annotator:
    volumes:
      - "./annotators/summarization_annotator:/src"
    ports:
      - 9058:9058
  dialog-summarizer:
    volumes:
      - "./services/dialog_summarizer:/src"
    ports:
      - 9059:9059
version: "3.7"
