# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242

  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8111:8111
  ranking-and-sf-based-response-selector:
    volumes:
      - "./response_selectors/ranking_and_sf_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 8082:8082
  dff-intent-responder-skill:
    volumes:
      - "./skills/dff_intent_responder_skill:/src"
      - "./common:/src/common"
    ports:
      - 8015:8015
  intent-catcher:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8114:8114
  ner:
    volumes:
      - './annotators/NER_deeppavlov:/src'
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8021:8021
  factoid-qa:
    volumes:
      - "./skills/factoid_qa:/src"
      - "./common:/src/common"
    ports:
      - 8071:8071
  kbqa:
    volumes:
      - "./annotators/kbqa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8072:8072
  entity-linking:
    volumes:
      - "./annotators/entity_linking:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8075:8075
  wiki-parser:
    volumes:
      - "./annotators/wiki_parser:/src"
      - "./common:/src/common"
    ports:
      - 8077:8077
  mongo:
    ports:
      - 27018:27018
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  text-qa:
    volumes:
      - "./services/text_qa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8078:8078
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8087:8087
  fact-retrieval:
    volumes:
      - "./annotators/fact_retrieval:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8100:8100
  entity-detection:
    volumes:
      - "./annotators/entity_detection:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8103:8103
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8228:8228
  prompt-selector:
    volumes:
      - "./annotators/prompt_selector:/src"
      - "./common:/src/common"
    ports:
      - 8136:8136
  property-extraction:
    volumes:
      - "./annotators/property_extraction:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8236:8236
  dff-dream-faq-prompted-skill:
    volumes:
      - "./skills/dff_template_prompted_skill:/src"
      - "./common:/src/common"
    ports:
      - 8170:8170
  openai-api-chatgpt:
    volumes:
      - "./services/openai_api_lm:/src"
      - "./common:/src/common"
    ports:
      - 8245:8245
  summarization-annotator:
    volumes:
      - "./annotators/summarization_annotator:/src"
    ports:
      - 8058:8058
  dialog-summarizer:
    volumes:
      - "./services/dialog_summarizer:/src"
    ports:
      - 8059:8059
  dialogpt:
    volumes:
      - "./services/dialogpt:/src"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8126:8126
  speech-function-classifier:
    volumes:
      - "./annotators/speech_function_classifier:/src"
    ports:
      - 8108:8108
  speech-function-predictor:
    volumes:
      - "./annotators/speech_function_predictor:/src"
    ports:
      - 8107:8107
version: "3.7"
