SERVICE_PORT: 8186
SERVICE_NAME: dff_meeting_analysis_skill
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt-long.json
GENERATIVE_TIMEOUT: 120
SHORT_GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
SHORT_GENERATIVE_SERVICE_CONFIG: openai-chatgpt-long.json
SHORT_GENERATIVE_TIMEOUT: 30
N_UTTERANCES_CONTEXT: 7
FILE_SERVER_TIMEOUT: 30.0
