# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  multilingual-convers-evaluator-annotator:
    volumes:
      - "./annotators/MultilingualConversationEvaluator:/src"
    ports:
      - 8124:8124
  convers-evaluation-selector:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  mgpt:
    volumes:
      - "./services/mgpt:/src"
    ports:
      - 8125:8125
  multilingual-toxic-classification:
    volumes:
      - "./annotators/MultilingualToxicClassification:/src"
    ports:
      - 3613:3613
  multilingual-emotional-classification:
    volumes:
      - "./annotators/MultilingualEmotionalClassification:/src"
    ports:
      - 3665:3665
  multilingual-sentiment-classification:
    volumes:
      - "./annotators/MultilingualSentimentClassification:/src"
    ports:
      - 3668:3668
version: "3.7"
