# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  sentence-ranker:
    volumes:
      - "./annotators/sentence_ranker:/src"
    ports:
      - 8130:8130
  convers-evaluation-selector:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  mgpt:
    volumes:
      - "./services/mgpt:/src"
    ports:
      - 8126:8126
  toxic-classification:
    volumes:
      - "./annotators/MultilingualToxicClassification:/src"
    ports:
      - 8127:8127
  emotional-classification:
    volumes:
      - "./annotators/MultilingualEmotionalClassification:/src"
    ports:
      - 8128:8128
  sentiment-classification:
    volumes:
      - "./annotators/MultilingualSentimentClassification:/src"
    ports:
      - 8129:8129
version: "3.7"
