services:
  agent:
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run -ch http_client -pl assistant_dists/dream_multilingual/pipeline_conf.json --cors'
    environment:
      WAIT_HOSTS: "sentence-ranker:8130, convers-evaluation-selector:8009, 
          mgpt:8132, emotion-classification 8128:8128, toxic-classification 8127:8127,
          sentimemt-classification 8129:8129"
      WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-480}
  sentence-ranker:
    env_file: [.env]
    build:
      args:
        SERVICE_PORT: 8130
        PRETRAINED_MODEL_NAME_OR_PATH: DeepPavlov/bert-base-multilingual-cased-sentence
      context: .
      dockerfile: ./annotators/sentence_ranker/Dockerfile
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G

  convers-evaluation-selector:
    env_file: [.env]
    build:
      args:
        TAG_BASED_SELECTION: 1
        CALL_BY_NAME_PROBABILITY: 0.5
        PROMPT_PROBA: 0.3
        ACKNOWLEDGEMENT_PROBA: 0.3
        PRIORITIZE_WITH_REQUIRED_ACT: 1
        PRIORITIZE_NO_DIALOG_BREAKDOWN: 0
        PRIORITIZE_WITH_SAME_TOPIC_ENTITY: 1
        IGNORE_DISLIKED_SKILLS: 0
        GREETING_FIRST: 1
        RESTRICTION_FOR_SENSITIVE_CASE: 1
        PRIORITIZE_PROMTS_WHEN_NO_SCRIPTS: 0
        ADD_ACKNOWLEDGMENTS_IF_POSSIBLE: 1
        PRIORITIZE_SCRIPTED_SKILLS: 0
      context: .
      dockerfile: ./response_selectors/convers_evaluation_based_selector/Dockerfile
    command: flask run -h 0.0.0.0 -p 8009
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  mgpt:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8132
        SERVICE_NAME: mgpt
        CONFIG: mgpt.json
        PRETRAINED_MODEL_NAME_OR_PATH: sberbank-ai/mGPT
        N_HYPOTHESES_TO_GENERATE: 5
      context: ./services/mgpt/
    command: flask run -h 0.0.0.0 -p 8132
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 10G

  emotion-classification:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8128
        SERVICE_NAME:   emotion-classification
        PRETRAINED_MODEL_NAME_OR_PATH: MilaNLProc/xlm-emo-t
      context: ./annotators/MultilingualEmotionalClassification/
    command: flask run -h 0.0.0.0 -p 8128
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G

  toxic-classification:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8127
        SERVICE_NAME: toxic-classification
        PRETRAINED_MODEL_NAME_OR_PATH: https://github.com/unitaryai/detoxify/releases/download/v0.4-alpha/multilingual_debiased-0b549669.ckpt
      context: ./annotators/MultilingualToxicClassification/
    command: flask run -h 0.0.0.0 -p 8127
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G

  sentiment-classification:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8129
        SERVICE_NAME: sentiment-classification
        PRETRAINED_MODEL_NAME_OR_PATH: cardiffnlp/twitter-xlm-roberta-base-sentiment
      context: ./annotators/MultilingualSentimentClassification/
    command: flask run -h 0.0.0.0 -p 8129
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G
version: '3.7'
