services:
  sentence-ranker:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8130
      - PORT=8130

  convers-evaluation-selector:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8009
      - PORT=8009

  gpt2-generator:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8132
      - PORT=8126

  emotion-classication:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8038
      - PORT=8038

  toxic-classication:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8013
      - PORT=8013

  sentiment-classication:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8024
      - PORT=8024
version: '3.7'
