services:
  multilingual-convers-evaluator-annotator:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=lnsigo.mipt.ru:8004
      - PORT=8004

  convers-evaluation-selector:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=lnsigo.mipt.ru:8009
      - PORT=8009

  mgpt:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=lnsigo.mipt.ru:8125
      - PORT=8125

  multi-emotional-classication:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=lnsigo.mipt.ru:8125
      - PORT=8125

version: '3.7'
