services:
  sentence-ranker:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8130
      - PORT=8130

  convers-evaluation-selector:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8009
      - PORT=8009

  mgpt:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8132
      - PORT=8126

  emotional-classication:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8128
      - PORT=8128

  toxic-classication:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8127
      - PORT=8127

  sentiment-classication:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=dream.deeppavlov.ai:8129
      - PORT=8129
version: '3.7'
