services:
  agent:
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/da_costa_clothes_assistant/pipeline_conf.json'
    environment:
      WAIT_HOSTS: "sentseg:8011, oasst12b-based-response-selector:8003, badlisted-words:8018, combined-classification:8087, 
        sentence-ranker:8128, prompt-selector:8135, transformers-lm-oasst12b:8158, 
        dff-da-costa-clothes-prompted-skill:8144"
      WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-1000}

  sentseg:
    env_file: [ .env ]
    build:
      context: ./annotators/SentSeg/
    command: flask run -h 0.0.0.0 -p 8011
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1.5G

  combined-classification:
    env_file: [ .env ]
    build:
      args:
        CONFIG: combined_classifier.json
        SERVICE_PORT: 8087
      context: .
      dockerfile: ./annotators/combined_classification/Dockerfile
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G

  oasst12b-based-response-selector:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8003
        SERVICE_NAME: response_selector
        LANGUAGE: EN
        GENERATIVE_SERVICE_URL: http://transformers-lm-oasst12b:8158/respond
        GENERATIVE_SERVICE_CONFIG: default_generative_config.json
        GENERATIVE_TIMEOUT: 5
        N_UTTERANCES_CONTEXT: 5
        FILTER_TOXIC_OR_BADLISTED: 1
      context: .
      dockerfile: ./response_selectors/llm_based_response_selector/Dockerfile
    command: flask run -h 0.0.0.0 -p 8003
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M

  badlisted-words:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8018
        SERVICE_NAME: badlisted_words
      context: annotators/BadlistedWordsDetector/
    command: flask run -h 0.0.0.0 -p 8018
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  prompt-selector:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8135
        SERVICE_NAME: prompt_selector
        N_SENTENCES_TO_RETURN: 3
        PROMPTS_TO_CONSIDER: da_costa_clothes
      context: .
      dockerfile: ./annotators/prompt_selector/Dockerfile
    command: flask run -h 0.0.0.0 -p 8135
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M

  sentence-ranker:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8128
        SERVICE_NAME: sentence_ranker
        PRETRAINED_MODEL_NAME_OR_PATH: sentence-transformers/all-MiniLM-L6-v2
      context: ./services/sentence_ranker/
    command: flask run -h 0.0.0.0 -p 8128
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 3G

  transformers-lm-oasst12b:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8158
        SERVICE_NAME: transformers_lm_oasst12b
        PRETRAINED_MODEL_NAME_OR_PATH: OpenAssistant/oasst-sft-1-pythia-12b
        HALF_PRECISION: 1
      context: .
      dockerfile: ./services/transformers_lm/Dockerfile
    command: flask run -h 0.0.0.0 -p 8158
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 60G
        reservations:
          memory: 60G

  dff-da-costa-clothes-prompted-skill:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8144
        SERVICE_NAME: dff_da_costa_clothes_prompted_skill
        PROMPT_FILE: common/prompts/da_costa_clothes.json
        GENERATIVE_SERVICE_URL: http://transformers-lm-oasst12b:8158/respond
        GENERATIVE_SERVICE_CONFIG: default_generative_config.json
        GENERATIVE_TIMEOUT: 5
        N_UTTERANCES_CONTEXT: 7
      context: .
      dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8144 --reload
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

version: '3.7'
