# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  files:
    ports:
      - 3000:3000
    volumes:
      - "~/.deeppavlov/file_server:/tmp"
  dff-program-y-skill:
    volumes:
      - "./skills/dff_program_y_skill:/src"
      - "./common:/src/common"
    ports:
      - 8019:8019
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8039:8039
  convers-evaluation-selector:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  dff-intent-responder-skill:
    volumes:
      - "./skills/dff_intent_responder_skill:/src"
      - "./common:/src/common"
    ports:
      - 8043:8043
  intent-catcher:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8014:8014
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8056:8056
  voice-service:
    volumes:
      - "~/.deeppavlov/file_server:/tmp"
    ports:
      - 8333:8333
  dff-voice-skill:
    volumes:
      - "~/.deeppavlov/file_server:/tmp"
    ports:
      - 8444:8444
version: "3.7"
