emotion-classification-deepy:
- group: response_annotators
  connector:
    protocol: python
    url: http://emotion-classification-deepy:8015/model
    class_name: connectors:BatchConnector
  dialog_formatter: dp_formatters:hypotheses_list
  response_formatter: dp_formatters:simple_formatter_service
  previous_services:
  - skills
  state_manager_method: add_hypothesis_annotation_batch
