SERVICE_PORT: 8174
SERVICE_NAME: dff_fairytale_ru_prompted_skill
PROMPT_FILE: common/prompts/fairytale_ru.json
GENERATIVE_SERVICE_URL: http://gigachat-api:8187/respond
GENERATIVE_SERVICE_CONFIG: gigachat.json
GENERATIVE_TIMEOUT: 20
N_UTTERANCES_CONTEXT: 3
ENVVARS_TO_SEND: GIGACHAT_CREDENTIAL,GIGACHAT_SCOPE
