name: dff-external-integration-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8169
      SERVICE_NAME: dff_external_integration_skill
      EXTERNAL_SKILL_URL: future_url
      ARGUMENT_TO_SEND: message
    context: .
    dockerfile: ./skills/dff_external_integration_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8169 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - "./skills/dff_external_integration_skill:/src"
  - "./common:/src/common"
  ports:
  - 8169:8169
proxy: null
