dff-template-template-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 10.0
    url: http://dff-template-template-prompted-skill:template_port/respond
  dialog_formatter: state_formatters.dp_formatters:dff_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-ai-faq-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 10.0
    url: http://dff-ai-faq-prompted-skill:8143/respond
  dialog_formatter: state_formatters.dp_formatters:dff_ai_faq_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-fairytale-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 30.0
    url: http://dff-fairytale-prompted-skill:8139/respond
  dialog_formatter: state_formatters.dp_formatters:dff_fairytale_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-marketing-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 10.0
    url: http://dff-marketing-prompted-skill:8138/respond
  dialog_formatter: state_formatters.dp_formatters:dff_marketing_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-fashion-stylist-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 10.0
    url: http://dff-fashion-stylist-prompted-skill:8144/respond
  dialog_formatter: state_formatters.dp_formatters:dff_fashion_stylist_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-dream-persona-gpt-j-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 10.0
    url: http://dff-dream-persona-gpt-j-prompted-skill:8134/respond
  dialog_formatter: state_formatters.dp_formatters:dff_dream_persona_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-nutrition-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 10.0
    url: http://dff-nutrition-prompted-skill:8141/respond
  dialog_formatter: state_formatters.dp_formatters:dff_nutrition_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-life-coaching-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 7.0
    url: http://dff-life-coaching-prompted-skill:8142/respond
  dialog_formatter: state_formatters.dp_formatters:dff_life_coaching_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-dream-persona-davinci3-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 14.0
    url: http://dff-dream-persona-davinci3-prompted-skill:8137/respond
  dialog_formatter: state_formatters.dp_formatters:dff_dream_persona_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-deepy-terminology-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 14.0
    url: http://dff-deepy-terminology-prompted-skill:8148/respond
  dialog_formatter: state_formatters.dp_formatters:dff_deepy_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-deepy-prompt-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 14.0
    url: http://dff-deepy-prompt-prompted-skill:8152/respond
  dialog_formatter: state_formatters.dp_formatters:dff_deepy_prompt_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-dream-persona-llama7bru-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 10.0
    url: http://dff-dream-persona-llama7bru-prompted-skill:8151/respond
  dialog_formatter: state_formatters.dp_formatters:dff_dream_persona_ru_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-deeppavlov-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 15.0
    url: http://dff-deeppavlov-prompted-skill:8146/respond
  dialog_formatter: state_formatters.dp_formatters:dff_deeppavlov_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-casual-email-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 14.0
    url: http://dff-casual-email-prompted-skill:8154/respond
  dialog_formatter: state_formatters.dp_formatters:dff_casual_email_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-meeting-notes-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 14.0
    url: http://dff-meeting-notes-prompted-skill:8155/respond
  dialog_formatter: state_formatters.dp_formatters:dff_meeting_notes_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-official-email-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 14.0
    url: http://dff-official-email-prompted-skill:8156/respond
  dialog_formatter: state_formatters.dp_formatters:dff_official_email_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
dff-plan-for-article-prompted-skill:
- group: skills
  connector:
    protocol: http
    timeout: 14.0
    url: http://dff-plan-for-article-prompted-skill:8157/respond
  dialog_formatter: state_formatters.dp_formatters:dff_plan_for_article_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
