# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 8095:8095
  files:
    ports:
      - 3000:3000
    volumes:
      - "~/.deeppavlov/file_server:/tmp"
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  ranking-based-response-selector:
    volumes:
      - "./response_selectors/ranking_based_response_selector:/src"
      - "./common:/src/common"
    ports:
      - 8002:8002
  dff-program-y-skill:
    volumes:
      - "./skills/dff_program_y_skill:/src"
      - "./common:/src/common"
    ports:
      - 8008:8008
  dff-intent-responder-skill:
    volumes:
      - "./skills/dff_intent_responder_skill:/src"
      - "./common:/src/common"
    ports:
      - 8012:8012
  intent-catcher:
    volumes:
      - "./annotators/IntentCatcherTransformers:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8019:8019
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128
  prompt-selector:
    volumes:
      - "./annotators/prompt_selector:/src"
      - "./common:/src/common"
    ports:
      - 8135:8135
  vidchapters-service:
    volumes:
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8045:8045
  dff-vidchapters-skill:
    volumes:
      - "./skills/dff_vidchapters_skill:/src"
      - "./common:/src/common"
    ports:
      - 8046:8046 
  fromage:
    volumes:
      - "./services/fromage:/src"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8069:8069
  dff-fromage-image-skill:
    volumes:
      - "./skills/dff_fromage_image_skill:/src"
      - "./common:/src/common"
    ports:
      - 8070:8070
  voice-service:
    volumes:
      - "~/.deeppavlov/file_server:/tmp"
    ports:
      - 8333:8333
  dff-voice-skill:
    volumes:
      - "~/.deeppavlov/file_server:/tmp"
    ports:
      - 8444:8444
version: "3.7"
